### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by easyw** [microelly2/geodata#12]
Unfortunately GeoData is not py3 complaint ATM.
Would you please have a look at it? 
FC is going toward py3 and I would like to have this WB py3 ready too 😄

**Comment by luzpaz** [comment]
Tracking via https://github.com/FreeCAD/FreeCAD-addons/issues/93

**Comment by luzpaz** [comment]
@microelly2 When invoking from CLI I see:
```
During initialization the error Missing parentheses in call to 'print'. Did you mean print("run import ...")? (<string>, line 108) occurred in /home/beast/.FreeCAD/Mod/geodata/InitGui.py
Please look into the log file for further information
```
Running:
```
OS: Manjaro Linux
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.15609 (Git) AppImage
Build type: Release
Branch: master
Hash: a14af0f2bd26f980d71be80a799ee48127bc7619
Python version: 3.6.7
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)
```

**Comment by luzpaz** [comment]
```
Traceback (most recent call last):
  File "<string>", line 120, in InitApplications
  File "<string>", line 108
    print "run import ..."
                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("run import ...")?
----------------------------------------------------------------------------------------------------
During initialization the error Missing parentheses in call to 'print'. Did you mean print("run import ...")? (<string>, line 108) occurred in /home/foo/.FreeCAD/Mod/geodata/InitGui.py
Please look into the log file for further information
```

**Comment by elliotclee** [comment]
bump... Main changes that need to be made are using print as a function, doing 'from importlib import reload' anywhere that reload() is used, and using != operator instead of <>.

**Comment by elliotclee** [comment]
[geodata-python3.zip](https://github.com/microelly2/geodata/files/2897464/geodata-python3.zip)

Did the grunt work in the attached patch. I think there are still some issues that come from Qt5, since when I tried to import OSM or Lidar data, it popped up empty dialog boxes.
