### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by pandaiolo** [microelly2/geodata#14]
Hi!

I am trying to make this module work on my Mac

Here are my progresses so far:

In `navigator.py`, I have changed:

```diff
- mw=QtGui.qApp  # this was `None` and methods call would fail
+ mw=QtGui.QApplication
```

(there are two occurrences in that file)

Now, I am stuck on the following error:
```diff
- Running the Python command 'Navigator' failed:
- Traceback (most recent call last):
-   File "<string>", line 245, in Activated
-   File "/Applications/FreeCAD.app/Contents/Mod/geodata/geodat/navigator.py", line 1168, in navi
-    mw.installEventFilter(ef)
-
- installEventFilter() takes exactly one argument (0 given)
```

The line is the following in `navigator.py`:
```js
mw.installEventFilter(ef)
```

Interestingly, when I test the value of `ef` before this call, it is correctly defined, so I don't know what is the issue.

Any idea?

Thanks!

**Comment by pandaiolo** [comment]
New modifications:

```diff
- mw.installEventFilter(ef)
+ mw.instance().installEventFilter(ef)
```

(same for `removeEventFilter`)

```diff
-  widget = QtGui.qApp.widgetAt(self.lastpos) # Cannot find widgetAt of 'None'
+  if self.lastpos:
+      widget = QtGui.QApplication.widgetAt(self.lastpos)
+   else:
+      widget = None
```

Now the control appear, and they seem to respond to mouse event. But I have yet to find how to make keyboard work, and the main view is pitch black....

**Comment by pandaiolo** [comment]
Another batch of updates got me running this addon with success on my Mac!

Change the lines that test the type of events with new version of `PySide`, like below:

```diff
- if z == 'PySide.QtCore...
+ if z == 'PySide2.QtCore...
```

On a Macbook, the arrow keys are not `Top`, `Right`, etc, but instead `Keypad-Top`, `Keypad-Right`, etc.

I replaced the occurrences of them in the code to be able to use normal keyboard arrow keys.

Example: 

```diff
- if ef.mode=='turn':
-   if keystring=='Up':
-     ef.breite += 1.0
-   if keystring=='Down':
+ if ef.mode=='turn':
+   if keystring=='Keypad-Up':
+     ef.breite += 1.0
+   if keystring=='Keypad-Down':
```
I also discovered that you can place the camera correctly by pressing `F12` after launching the navigator.

I now have a working solution and the different modes seem to work.

Let me know if you have any questions. I can push a PR if someone's interested, or if anyone is willing to test my changes with non-mac setups.
