### ISSUE TITLE
Error while importing say package

### ISSUE THREAD

**Issue by JoseanIrun** [microelly2/geodata#4]
Hi @microelly2,

I am totally new at GitHub and a non very experienced user of FreeCAD. 
Firstly, I want to give you thanks for your public and kindly distributed work**S**.

I have some problems (I hope this is the place to report this kind of problem) using Geodat. I have already copied Geodat inside Mod folder and I am FreeCAD_0.17.8443_x64_dev_win on Win7 Ultimate.

Some of the features work, such as Navigator, but those that call say Python packages do not work.

I have type in the Python console next: and received the next message:

_>>> from say import *_
_Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\ING\FreeCAD\c_0.17_pre\FreeCAD_0.17.8443_x64_dev_win\bin\lib\site-packages\say-1.4.2-py2.7.egg\say\__init__.py", line 1, in <module>
    from .core import say, Say, SayReturn, fmt, Fmt, caller_fmt, FmtException, numberer
  File "C:\ING\FreeCAD\c_0.17_pre\FreeCAD_0.17.8443_x64_dev_win\bin\lib\site-packages\say-1.4.2-py2.7.egg\say\core.py", line 149, in <module>
    class Say(object):
  File "C:\ING\FreeCAD\c_0.17_pre\FreeCAD_0.17.8443_x64_dev_win\bin\lib\site-packages\say-1.4.2-py2.7.egg\say\core.py", line 159, in Say
    files=[get_stdout()], # where is output headed? a list of write() able objects
  File "C:\ING\FreeCAD\c_0.17_pre\FreeCAD_0.17.8443_x64_dev_win\bin\lib\site-packages\say-1.4.2-py2.7.egg\say\core.py", line 104, in get_stdout
    if sys.stdout.encoding == 'UTF-8':
AttributeError: encoding_

I am nearly sure that this malfunction is due to some lack in my installation or maybe some library is missing (I found say inside .\FreeCAD_0.17.8443_x64_dev_win\bin\Lib\site-packages, I also installed from the .zip I downloaded). My Python version in PC is 2.7.12 for 32bit.

Thank you for your time!

Josean

**Comment by microelly2** [comment]
thank you for trying to use this workbench.

I use my own say module, but it is part of the animation workbench, so it's still not installed on your system.

I never before have used the https://pypi.python.org/pypi/say/.

I will put my say file into the git project
and test it.

I still have never tested geodat wb for windows,
maybe there come other errors too.
I will put it into my task list for the next weeks.
I report the results here.
