### ISSUE TITLE
Import fail 

### ISSUE THREAD

**Issue by kurt771** [microelly2/geodata#5]
Hi microelly2

Thanks for the great idea to implement geodata in FreeCad.
I tried to use your workbench function Import.
I get following errors independent what I choice osm, csv, xyz,...

Running the Python command 'Import OSM Map' failed:
Traceback (most recent call last):
File "<string>", line 165, in Activated
File "C:\Users\Kurt\AppData\Roaming\FreeCAD\Mod\geodata-master\geodat\__init__.py", line 2, in <module>
import geodat.import_aster
File "C:\Users\Kurt\AppData\Roaming\FreeCAD\Mod\geodata-master\geodat\import_aster.py", line 23, in <module>
import geodat.geodat_lib
File "C:\Users\Kurt\AppData\Roaming\FreeCAD\Mod\geodata-master\geodat\geodat_lib.py", line 11, in <module>
import cv2

No module named cv2

Environment:
OS: Windows 8.1
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.16.6706 (Git)
Build type: Release
Branch: releases/FreeCAD-0-16
Hash: f86a4e411ff7848dea98d7242f43b7774bee8fa0
Python version: 2.7.8
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 6.8.0.oce-0.17

Please can you help on this error
Thanks in advance and greetings from the nice area
Upperaustria
Kurt

**Comment by kurt771** [comment]
Hi Microelly2, for your info

I haven’t had any success with windows to run the import of geodata.

I switched the operating system to Fedora V25, but I had other problems eg. freecad crashing with memory exceptions.
After installing Kubuntu 16.10 with the necessary modules opencv and gdal, no major problems.

There are some minor issues eg. when importing OSM height, the coordinates calculation midpoint lat and plus/minus calculation is shifted, but I found a workaround. I'll be waiting for your next update.

Thanks for your outstanding work

**Comment by flywire** [comment]
Errors not reported to user (eg point defined twice cannot be resolved). Program should display warning and skip second point.
